from .start import start_handler
from .help import help_handler
from .error import error_handler
from .callback_query import callback_query_handler
from .interview import interview_handler
from .courses import courses_handler
from .lectures import lectures_handler
from .practice_platforms import practice_platforms_handler
from .essential_skills import essential_skills_handler
