version: '3.1'

services:
    backend:
        image: ds-advisor-backend
        container_name: backend
        build:
            context: .
            dockerfile: backend.dockerfile
        environment:
            - DATA_STORAGE_URL=mongodb://data_storage:27017
            - DATA_STORAGE_USERNAME=defUser
            - DATA_STORAGE_PASSWORD=defPass
            - DATA_STORAGE_NAME=ds_advisor
            - TELEGRAM_TOKEN=PUT_YOUR_TELEGRAM:TOKEN_HERE
        depends_on:
            - data_storage
            - data_storage_init
        links:
            - data_storage:data_storage
        network_mode: bridge
        restart: always
    
    data_storage:
        image: mongo:4.2.5
        container_name: data_storage
        environment:
            - MONGO_INITDB_ROOT_USERNAME=defUser
            - MONGO_INITDB_ROOT_PASSWORD=defPass
        volumes:
            - ./storage-volume:/data/db
        network_mode: bridge
        restart: always

    data_storage_init:
        image: ds-advisor-data-storage-init
        container_name: data_storage_init
        build:
            context: .
            dockerfile: data_storage_init.dockerfile
        environment:
            - DATA_STORAGE_USERNAME=defUser
            - DATA_STORAGE_PASSWORD=defPass
            - DATA_STORAGE_DB_NAME=ds_advisor
            - DATA_STORAGE_URL=mongodb://data_storage:27017
        links:
            - data_storage:data_storage
        network_mode: bridge
        depends_on:
            - data_storage
